# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0002_auto_20170413_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isLogin',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='isValid',
            field=models.NullBooleanField(),
        ),
    ]
