# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0004_auto_20170417_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonrpcserverinfo',
            name='enable',
            field=models.NullBooleanField(),
        ),
    ]
