# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0005_jsonrpcserverinfo_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonrpcserverinfo',
            name='usingSequence',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jsonrpcserverinfo',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
