# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0006_auto_20170417_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonrpcserverinfo',
            name='usingSequence',
        ),
        migrations.AddField(
            model_name='jsonrpcserverinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonrpcserverinfo',
            name='priority',
            field=models.IntegerField(choices=[(0, 'debug'), (1, 'public'), (2, 'private')], default=0),
            preserve_default=False,
        ),
    ]
