# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0007_auto_20170417_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonrpcserverinfo',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Debug'), (1, 'Public'), (2, 'Private')]),
        ),
    ]
