# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0008_auto_20170417_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('toUser', models.CharField(max_length=120)),
                ('coins', models.CharField(max_length=120)),
                ('date', models.CharField(max_length=120)),
            ],
        ),
    ]
