# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.CharField(default='test', max_length=128),
        ),
    ]
