# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0010_transaction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Coins',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
