# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0011_account_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='_isSubmited',
            field=models.NullBooleanField(),
        ),
    ]
