# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0012_account__issubmited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='_isSubmited',
        ),
        migrations.AddField(
            model_name='account',
            name='is_submited',
            field=models.NullBooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='isLogin',
            field=models.NullBooleanField(editable=False),
        ),
    ]
