# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0013_auto_20170505_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='isLogin',
            new_name='is_Login',
        ),
    ]
