# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0014_auto_20170505_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, '一般交易'), (1, '特權交易'), (2, '特權派發')], default=0),
            preserve_default=False,
        ),
    ]
