# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0015_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonrpcserverinfo',
            name='controlAdminAccount',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonrpcserverinfo',
            name='controlAdminPassword',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Normal Transfer'), (1, 'Admin Transfer'), (2, 'Admin Assgin')]),
        ),
    ]
