# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0019_auto_20170508_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonrpcserverinfo',
            name='controlAdminAccount',
        ),
        migrations.RemoveField(
            model_name='jsonrpcserverinfo',
            name='controlAdminPassword',
        ),
    ]
