# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactor', '0021_auto_20170508_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonrpcserverinfo',
            name='controlAdminPassword',
        ),
    ]
